### ISSUE TITLE
Crazy output and unable to exit tomato app until closing terminal window

### ISSUE THREAD

**Issue by luisnquin** [gabrielzschmitz/Tomato.C#12]
The problem occurs directly when starting the program, there's no menu, just that

Also ignore the second and third zsh error, is a zsh plugin

![image](https://user-images.githubusercontent.com/86449787/214474739-fdfbf492-a6df-4a2b-bab8-cdf2e5db0e93.png)

These are my specs:
**OS**: NixOS
**Zsh version**: 5.9 (x86_64-pc-linux-gnu)
**prompt**: Starship(I think that's irrelevant but)

**used tomato rev**: 3c7cba14b78a771dfb982420410dd197f6e09954

**Comment by gabrielzschmitz** [comment]
I think that's because now I need to run the `make install` as regular user (without sudo), as you can see:
https://github.com/gabrielzschmitz/Tomato.C/commit/1a4b0c759d1e3fd8602e9237a40bcb3892d6d314

Is there any way of achieving this with a nix pkg?

**Comment by luisnquin** [comment]
I can't research more about that by now(maybe later), but I don't think that's a sudo problem, if Nix doesn't seems something ok with the package then it only throws an error that doesn't allow you to pass the package to your machine

Wait for news

**Comment by gabrielzschmitz** [comment]
The crash occours because you can't write to the log file or because the log file is at the wrong folder (config.mk):

```c
LOGPREFIX=$(HOME)/.local/share/tomato
```
because the HOME was probably at /root instead of /home/username

**Comment by gabrielzschmitz** [comment]
Now it should work fine, moved the log folder and file creation to runtime. Try it and give me a feedback

**Comment by luisnquin** [comment]
Yeah, it's finally working, thanks for your support @gabrielzschmitz

![image](https://user-images.githubusercontent.com/86449787/214728599-8c65f1e8-1667-4328-88e3-67e72732c338.png)
![image](https://user-images.githubusercontent.com/86449787/214728619-5591a5d9-0060-405b-a5c8-5c73447fd6e3.png)

**Comment by gabrielzschmitz** [comment]
Happy it worked :)
