### ISSUE TITLE
Give more details of the previous tomato session

### ISSUE THREAD

**Issue by luisnquin** [gabrielzschmitz/Tomato.C#16]
Good day, I just wanted to suggest a feature for the resume prompt:)

![image](https://user-images.githubusercontent.com/86449787/220234690-75d71146-236c-4458-9850-faf40a6b2d7f.png)

As a user maybe I should also want to see the previous number of pomodoros done and the time remaining

Take it as something what could improve the experience when having to decide whether or not to resume

**Comment by gabrielzschmitz** [comment]
You're absolutelly right, I've tried to implemented it at first, but have no idea where to put it! Do you have any idea?

I've come out with this:
NOW/
THEN
![image](https://user-images.githubusercontent.com/58743811/220343452-1e800d8e-9c03-4676-a10e-4e6505b58581.png)

Have you any better idea?

**Comment by luisnquin** [comment]
Nice one, I like it

The normal thing is the `Yes` in the left side as you can see below
![image](https://user-images.githubusercontent.com/86449787/220389775-9a93f288-f136-4ebb-ab22-cf5146aef99a.png)

I don't have a good idea of where to put that two items of the previous session, anyway you can inspire you by searching

`yes no video game prompt`

Or even the message to continue a video in Youtube

**Comment by gabrielzschmitz** [comment]
Here's what I've done: 

![untitled](https://user-images.githubusercontent.com/58743811/220463101-35e9a2da-680d-4280-b97e-22d9238b90fc.gif)

If you have any idea make a new issue ;)

**Comment by luisnquin** [comment]
1/4🍅 is enough IMO
