### ISSUE TITLE
add newline to goodbye messages

### ISSUE THREAD

**Issue by ghost** [gabrielzschmitz/Tomato.C#17]
in file `input.c` the Lines 195, 405, 432 contain the message "Goodbye!" without a newline. Maybe adding one would be better :) 

related PR here: https://github.com/gabrielzschmitz/Tomato.C/pull/18

**Comment by gabrielzschmitz** [comment]
Sure! Could you redo the PR following the PR title template (File-Related-Emoji Tittle)?

**Comment by ghost** [comment]
@gabrielzschmitz Hope this is okay https://github.com/gabrielzschmitz/Tomato.C/pull/19

**Comment by gabrielzschmitz** [comment]
Yes, it is. Thanks!
