### ISSUE TITLE
Some icons doesn't show up

### ISSUE THREAD

**Issue by tienbuigia** [gabrielzschmitz/Tomato.C#20]
![image](https://file.io/WGvgfyipWTgS)

Hi, I really love this tomato timer.

How do you find the 'sprites'? Did you just design it yourself?

Oh and I have nerdfont, noto-color-emoji, fontawesome but still some icons doesn't do right.
I installed them all by pacman in official arch repo.

**Comment by tienbuigia** [comment]
Also, this is my fonts.conf
```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>

	<alias>
		<family>monospace</family>
		<prefer>
			<family>JetBrainsMono Nerd Font Mono</family>
			<family>Iosevka Nerd Font Mono</family>
			<family>Noto Color Emoji</family>
		</prefer>
	</alias>
	<alias>
		<family>sans-serif</family>
		<prefer>
			<family>Iosevka Aile</family>
			<family>Noto Color Emoji</family>
			<family>Noto Sans</family>
		</prefer>
	</alias>
	<alias>
		<family>serif</family>
		<prefer>
			<family>Iosevka Etoile</family>
			<family>Noto Color Emoji</family>
			<family>Noto Serif</family>
		</prefer>
	</alias>
</fontconfig>
```

**Comment by luisnquin** [comment]
Hi @tienbuigia, fix your image of your first comment, it doesn't display very well

**Comment by tienbuigia** [comment]
it's Ok, I found the issue. It's nerdfonts version 3.0 deprecated some icons. I'll make a pull request.
