### ISSUE TITLE
can't go 75+15 method

### ISSUE THREAD

**Issue by aurkaxi** [gabrielzschmitz/Tomato.C#22]
I regularly work in 75+15 method. but i can't go higher than 50 work time in this program. How do i bypass this?

**Comment by gabrielzschmitz** [comment]
Just change this line in `input.c`, `settingsInput(appData * app, char key)` function:
```c
        else if(app->menuPos == 2){
-            if(app->workTime != (50 * 60 * 8))
+            if(app->workTime != (75 * 60 * 8))
                app->workTime = app->workTime + (5 * 60 * 8);
        }
```

Hope this is helpful for you!

**Comment by aurkaxi** [comment]
Thank you. <3.
Also thanks for having make uninstall functionality.

**Comment by aurkaxi** [comment]
You even increased it the repo. woah. thank you.
