### ISSUE TITLE
Feature request - disable autostart 

### ISSUE THREAD

**Issue by MrKugga** [gabrielzschmitz/Tomato.C#28]
Hi! First of all, you did a really great job on this project, thank you! 

I just wanted to suggest a feature which I could not find. Would it be possible to implement a setting to disable autostart of the focus/break period?

Thanks!

**Comment by gabrielzschmitz** [comment]
Sure! It's done: **57dc8bb2c0d197942fbae15fcb2559dd6682471a**

Hope it helps you! You just need to change `AUTOSTARTWORK` and/or `AUTOSTARTPAUSE` to 0.

**Comment by MrKugga** [comment]
Thank you so much! You're the best!
