### ISSUE TITLE
Timer not run when opening notepad

### ISSUE THREAD

**Issue by tienbuigia** [gabrielzschmitz/Tomato.C#30]
Hi, I've been using tomato.c daily, thanks to you.

Lately, I notice we have new feature, it's notepad. So instead of open a vim buffer to write tasks, I use this instead.

I was doing tasks for hours until I realize I did not receive any break time reward because I was keeping the note open.

And when you pause, the note won't show anything.

Thank you again.

**Comment by gabrielzschmitz** [comment]
Try it out now, and give me some feedback! It should be implemented.

**Comment by tienbuigia** [comment]
Sorry for the slow response, Time is definitely running when open notepad now, but fixing this seems to generated another problem.

Now when I switch focus from tomato to another application or back to tomato, it seems to receive a `q`, and quit out. Tested on dwm and Hyprland.

**Comment by gabrielzschmitz** [comment]
Looks like the program is getting ALT+NUMBER like a ESC, for some reason. Please make a new issue, just to separate the problems 😅
