### ISSUE TITLE
ALT+NUM = ESC

### ISSUE THREAD

**Issue by gabrielzschmitz** [gabrielzschmitz/Tomato.C#31]
Sorry for the slow response, Time is definitely running when open notepad now, but fixing this seems to generated another problem.

Now when I switch focus from tomato to another application or back to tomato, it seems to receive a `q`, and quit out. Tested on dwm and Hyprland.

_Originally posted by @tienbuigia in https://github.com/gabrielzschmitz/Tomato.C/issues/30#issuecomment-1868222691_

**Comment by gabrielzschmitz** [comment]
Adding this check statement at input.c seems to fix the problem:

```c
      case ESC:
      case CTRLC:
      case 'q':
+        if (getch() != -1) break;
```

**Comment by tienbuigia** [comment]
Yes, it is working smoothly now. Thank you.

**Comment by gabrielzschmitz** [comment]
No problem my man! Any other problem just commit a issue :)
