### ISSUE TITLE
Feature to skip pause, break, and pomodoro

### ISSUE THREAD

**Issue by windowschips** [gabrielzschmitz/Tomato.C#33]
Add a button or keybind to skip the short breaks, long breaks, and the working times.

**Comment by gabrielzschmitz** [comment]
Sure! I'll let you know when this feature is available :)

**Comment by gabrielzschmitz** [comment]
Made in 8f546f04a81486f46d8f51bbb0a97ecb64d59e46, try it out! Just need to press `s` or `ctrl+s` or click the icon next to the pause to skip a section.
