### ISSUE TITLE
Some icons are not being displayed

### ISSUE THREAD

**Issue by avii1103** [gabrielzschmitz/Tomato.C#35]
![image](https://github.com/gabrielzschmitz/Tomato.C/assets/86581604/80ad23be-4755-40df-8ada-9d21ac9b70cf)
OS: Linux mint 21.3, kernel 6.5.0

**Comment by gabrielzschmitz** [comment]
Are you using a Nerd Font Patched font in your terminal?

**Comment by avii1103** [comment]
> Are you using a Nerd Font Patched font in your terminal?

No, I'm just using my system default monospace font, "deja vu sans mono book"

**Comment by gabrielzschmitz** [comment]
Then you should change the `ICONS` at `config.h` from "nerdfont" to "icons" and recompile or change your terminal font to a properly nerd font patched font.

**Comment by gabrielzschmitz** [comment]
Is it working for you now?
