### ISSUE TITLE
I'm not able to see the notebook or to add a note/task

### ISSUE THREAD

**Issue by CarlosCraveiro** [gabrielzschmitz/Tomato.C#40]
I'm using NixOS, and I have built the application by running the following

```bash
git clone https://github.com/gabrielzschmitz/Tomato.C.git
cd Tomato.C
nix develop
nix build
nix run
```

When I try to add a note I don't see the "cute notebook", only getting what appears to be a white cursor...however, when I try to add a note, sometimes I can type something, sometimes I get a segmentation fault.

![Screenshot-2024-03-23_17-34-03](https://github.com/gabrielzschmitz/Tomato.C/assets/85318248/7f568ee2-121f-42f2-ab45-65493e827c7b)
![Screenshot-2024-03-23_17-34-49](https://github.com/gabrielzschmitz/Tomato.C/assets/85318248/9cf2261b-d9b5-4394-8a6b-0e7ae6342bb4)

**Comment by MeowRosya** [comment]
You may not be able to see because the color of the ascii charactrers in the notebook matches the color of the background. I faced the same problem and it was solved by changing the color of background.

**Comment by gabrielzschmitz** [comment]
Yeah, not sure about the segmentation fault. But the black in black print should be resolved now! Try git pulling the project and reinstalling.

Try fixing it first, than I will take a look at the notepad problem.

**Comment by CarlosCraveiro** [comment]
Now the notepad works!
![Screenshot-2024-03-23_21-27-36](https://github.com/gabrielzschmitz/Tomato.C/assets/85318248/cf32af28-5243-46f7-9d1b-7a5de29fefca)

**Comment by CarlosCraveiro** [comment]
However, as for seg-faults. Apparently, they occur when I accidentally end up changing the Pomodoro, like skipping steps or pausing it when I'm inside the notebook.

**Comment by gabrielzschmitz** [comment]
Should be fixed! I've really just forgot to block the skip input out of pomodoro...
Added mouse support to the skip icon too, you can just click it now!

**Comment by CarlosCraveiro** [comment]
Apparently it's working now. However, I noticed that I'm also getting segmentation faults inside the Pomodoro screen. Either by pressing 's' to skip or using the mouse. I also think that smoke should be comming out of the coffee...

![Skip_bug_click](https://github.com/gabrielzschmitz/Tomato.C/assets/85318248/34951833-ce91-4313-82fb-81b6d5cb6262)

**Comment by gabrielzschmitz** [comment]
Don't have any idea about it yet...

**Comment by gabrielzschmitz** [comment]
Try this patch at `input.c`:

```patch
--- input.c	2024-03-24 10:56:42.455462772 -0300
+++ input.c	2024-03-24 10:56:49.376571068 -0300
@@ -361,7 +361,7 @@

       case CTRLS:
       case 's':
-        if (app->currentMode >= 1 && app->currentMode <= 3) app->timer = 0;
+        if (app->currentMode >= 1 && app->currentMode <= 3) app->timer = 2;
         break;

       case ESC:
@@ -867,7 +867,7 @@
   if (app->currentMode >= 1 && app->currentMode <= 3) {
     if (event.y == (app->middley - 7) && (app->middlex - 10) >= event.x &&
         event.x >= (app->middlex - 11)) {
-      if (event.bstate & BUTTON1_PRESSED) app->timer = 0;
+      if (event.bstate & BUTTON1_PRESSED) app->timer = 2;
     }
   }
 }
```

Copy this code to a `patch.diff` file in the repository directory and just run the patch command:
```shell
patch input.c < patch.diff
```

Than, you just need to recompile the app to take effect:
```shell
sudo make clean install
```

Does this help?

**Comment by CarlosCraveiro** [comment]
Apparently the problem was an uninitialized variable `app->machineFrame`.
