### ISSUE TITLE
The notebook doesn't open while the Pomodoro is paused

### ISSUE THREAD

**Issue by CarlosCraveiro** [gabrielzschmitz/Tomato.C#43]
## Problem:
I discovered that the notebook doesn't open if the pomodoro is paused. I assume it's a bug.

![Bug_Open_notebook](https://github.com/gabrielzschmitz/Tomato.C/assets/85318248/7e3324e7-9ac5-4833-b7c1-7a864c27a6dc)

**Comment by CarlosCraveiro** [comment]
I can try to hunt down this bug and resolve it. But, I'm reporting first.

**Comment by gabrielzschmitz** [comment]
I can fix that one. Till tomorrow will be fixed!

**Comment by gabrielzschmitz** [comment]
Fixed!
