### ISSUE TITLE
Notes with more than one word do not remain after the app closes

### ISSUE THREAD

**Issue by CarlosCraveiro** [gabrielzschmitz/Tomato.C#44]
## Problem:
Notes with more than one word do not remain after the app closes. When returning, only the first word is saved.

![Bug_annotations_with_more_than_one_word](https://github.com/gabrielzschmitz/Tomato.C/assets/85318248/82d30863-64a2-4a00-b97a-ff1a0526ca2a)

**Comment by CarlosCraveiro** [comment]
As mentioned in the other issue #43. I can try to resolve this bug later myself, but I'm reporting first.

**Comment by gabrielzschmitz** [comment]
Fixed!
