### ISSUE TITLE
icon's of output 

### ISSUE THREAD

**Issue by nuexq** [gabrielzschmitz/Tomato.C#46]
![image](https://github.com/gabrielzschmitz/Tomato.C/assets/145666753/e661b665-df86-4365-9dbd-8aad14feea75)

i hope you remove the tomato icon whin the pomodoro is stoped

**Comment by CarlosCraveiro** [comment]
I think it's intuitive to keep both the current stage icon and the icon indicating the pause. Maybe adding an extra flag to adjust this could be a solution to please everyone.

**Comment by gabrielzschmitz** [comment]
Implemented! You just need to `git pull`, change the variable `TIMERLOGICONS` in `config.h` from 1 to 0. and recompile the app with `sudo make clean install`.
