### ISSUE TITLE
Freezes on Start in i3wm on Arch Linux

### ISSUE THREAD

**Issue by Ks4four** [gabrielzschmitz/Tomato.C#49]
**Specs:**

Running i3wm on Arch Linux.
i3 version: 4.23
kernel: 6.8.2-arch2-1

**Problem:**

Freezes when attempting to `start` from the menu. After approximately 30 seconds, it displays the error message: `error calling startservicebyname for org.freedesktop.secrets timeout was reached`.

I can't quit using `C-c` or `q`. It just freezes.

The app functions properly when executed with `sudo` privileges (which it shouldn't be). However, it still generates errors:

![2024-04-06_13-40](https://github.com/gabrielzschmitz/Tomato.C/assets/78544646/ba6733af-2008-457a-88ba-a1ea58262d62)

**Attempts:**

`sudo pacman -S gnome-keyring`: Already installed
`gnome-keyring-daemon --start --components=secrets`
`systemctl --user status dbus`: active

It works in my KDE Plasma 6.0.3, but I don't want to use Plasma.

**Comment by gabrielzschmitz** [comment]
Have you installed all the dependencies?
```shell
$ sudo pacman -S base-devel ncurses mpv pkgconf libnotify
```
looks something is wrong with pipewire, but just to be sure.

**Comment by Ks4four** [comment]
Yes, I have reinstalled dependencies, but still no help.

**Comment by gabrielzschmitz** [comment]
What happens if you disable `SOUNDS` and `NOISE` in `config.h`?

**Comment by Ks4four** [comment]
Tried
`static const int SOUND = 0;`
`static const int NOISE = 0;`
It didn't work.
I also restored the default i3 config, but nothing happens.

**Comment by gabrielzschmitz** [comment]
(You need to recompile to the changes in `config.h` take effect)

**Comment by Ks4four** [comment]
Yes, I forgot to mention that I did `sudo make install`.

**Comment by gabrielzschmitz** [comment]
Try commenting `MPVTOGGLE = 1` in `config.mk` too. As then mpv will be completely removed from the app.

**Comment by Ks4four** [comment]
Did it.

![2024-04-06_20-46](https://github.com/gabrielzschmitz/Tomato.C/assets/78544646/869b462a-6789-4d24-bfd9-e72db7882839)

Still freezes.
After like 100 seconds it starts the timer. Weird.

![2024-04-06_20-48](https://github.com/gabrielzschmitz/Tomato.C/assets/78544646/93a201fc-47d1-4516-a826-25037fc20223)

**Comment by gabrielzschmitz** [comment]
Dont switch 1 to 0. Actually comment the `MPVTOGGLE = 1` line.

Looks like there's problems with notifications too

**Comment by Ks4four** [comment]
Ahhh sorry. Did that comment just now. But nothing happens unfortunately

**Comment by gabrielzschmitz** [comment]
What happens when you
```shell
$ notify-send test
```

and when you
```shell
$ mpv sounds/dfltnotify.mp3
```

**Comment by Ks4four** [comment]
`Timeout was reached` after like 60s

**Comment by gabrielzschmitz** [comment]
After which command?

**Comment by Ks4four** [comment]
When `$ notify-send test` it says `Timeout was reached`
When `$ mpv sounds/dfltnotify.mp3` it says

```
[file] Cannot open file 'sounds/dfltnotify.mp3': No such file or directory
Failed to open sounds/dfltnotify.mp3.
Exiting... (Errors when loading file)
```

**Comment by Ks4four** [comment]
When `$ notify-send test` it says `Timeout was reached`
When `$ mpv sounds/dfltnotify.mp3`:

```
 (+) Audio --aid=1 (mp3 2ch 44100Hz)
File tags:
 Artist: FoolBoyMedia
 Comment: Created in Ignite, edited in Audition
AO: [pipewire] 44100Hz stereo 2ch floatp
(Paused) A: 00:00:01 / 00:00:01 (98%)
```

It played the music until it was paused at 98%

**Comment by gabrielzschmitz** [comment]
Looks like you don't have a notification daemon. Maybe try installing dunst, is a very minimal notification daemon:
```shell
$ sudo pacman -S dunst
```

then run it at background (should add to i3wm startup if works):
```shell
$ dunst &
```

then retry notify-send:
```
$ notify-send test
```

**Comment by Ks4four** [comment]
Ah it works. I just found out about the notification daemon.

`$ notify-send test` was successful and the timer works but I got this notification when resuming a timer:

`CRITICAL: Source ID 112 (or a random number) was not found when attempting to remove it`

but the timer is resuming the correct time. Does it matter?

**Comment by gabrielzschmitz** [comment]
Try adding dusnt to the i3wm startup and rebooting your machine.
```i3
exec --no-startup-id dunst
```

**Comment by Ks4four** [comment]
Got it 👌 No problems now.

**Comment by gabrielzschmitz** [comment]
If have any other problem, just open other issue, I'll be glad to help :)
