### ISSUE TITLE
Compilation terminated 

### ISSUE THREAD

**Issue by NischalDawadi** [gabrielzschmitz/Tomato.C#50]
cc -std=c99 -Wall -Wextra -pedantic -Wunused-result -Wno-unused-variable -Os -D_ISOC99_SOURCE -DTOMATONOISE=\"/usr/local/bin/tomatonoise\" -DLOGPREFIX=\".local/share/tomato\" -DLOGFILE=\".local/share/tomato/tomato.log\" -DTMPFILE=\".local/share/tomato/tmp.log\" -DTIMERFILE=\".local/share/tomato/time.log\" -DNOTEPADFILE=\".local/share/tomato/notepad.log\" -I/usr/local/include -L/usr/local/lib  tomatonoise.c  `pkg-config --libs ncursesw mpv` -o tomatonoise
Package mpv was not found in the pkg-config search path.
Perhaps you should add the directory containing `mpv.pc'
to the PKG_CONFIG_PATH environment variable
Package 'mpv', required by 'virtual:world', not found
tomatonoise.c:1:10: fatal error: mpv/client.h: No such file or directory
    1 | #include <mpv/client.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: tomatonoise] Error 1
FAIL

I am using fedora 39 
WM : Hyprland

**Comment by gabrielzschmitz** [comment]
Try installing all dependencies first:
```shell
$ sudo dnf groupinstall 'Development Tools' && sudo dnf install ncurses-devel mpv-devel pkgconf libnotify
```

Then:
```shell
$ sudo make install
```

**Comment by NischalDawadi** [comment]
Yes, it worked. mpv-devel was not mentioned in readme last time.

**Comment by gabrielzschmitz** [comment]
> Yes, it worked. mpv-devel was not mentioned in readme last time.

Yeah, my bad. Didn't know fedora splits librarys from programs like in Ubuntu.
