### ISSUE TITLE
Notification doesn't sound and tomatonoise high cpu usage

### ISSUE THREAD

**Issue by NischalDawadi** [gabrielzschmitz/Tomato.C#53]
when the session starts or finishes it only shows the notification but sound is not heard.

Also tomato noise has excessively high cpu usage..
if i enable all sound it goes upto 50% cpu usage.

Distro:Fedora 40
WM : Hyprland
Specs: Ryzen 5 4500u with 16gb ram

**Comment by CarlosCraveiro** [comment]
Since the problem is specifically related to audio notifications, perhaps it is something related to the [MPV](https://mpv.io/). It might be worth testing whether it's working properly.

Maybe try something like:
```bash
$ mpv <some_video_or_audio_file>
```
and see if the audio is outputting as it should.

**Comment by CarlosCraveiro** [comment]
In fact, the test can be done with tomato's own audio files, which in your distro I believe are in `/usr/local/share/tomato/sounds`.

Like:
```bash
$ mpv tomato/sounds/dfltnotify.mp3
```

**Comment by NischalDawadi** [comment]
there was no problem with mpv audio.
it was because of resume playback.. How to disable it for this cause ...it is handy while watching series and movies.

**Comment by CarlosCraveiro** [comment]
Ahh, fair enough..., but did you manage to solve this part of the problem then?

**Comment by CarlosCraveiro** [comment]
As for excessive CPU usage, now that you mention it, I observed the same on my machine. I tried running some profiling tools like `linux-perf` to see exactly what could be causing this, but I couldn't identify anything conclusive.
![Screenshot-2024-05-19_11-24-11](https://github.com/gabrielzschmitz/Tomato.C/assets/85318248/0583967d-6e73-4ccc-b082-83f92740b746)
In the screenshot you can see that the execution peaks of each `tomatonoise` processes go to around 50% CPU usage.

I currently tend to believe that this stems from the "pull-up loop" that exists within the `tomatonoise` to communicate with the tomato. If that's right (which I'm not sure), the solution would be to change how this is done, perhaps Unix Sockets could be and option to optimize the communication between processes...

But in this case, as I believe this is a problem with the way the code is structure (problem with the software architecture), an optimization regarding this would need to involve a discussion with more contributors.

**Comment by gabrielzschmitz** [comment]
I'm currently rewriting the app from the ground up, so the app performance should be ignored for now. But about the mpv error, did you manage to fix it?

**Comment by NischalDawadi** [comment]
I just disabled save on quit in mpv.
