### ISSUE TITLE
[Question] AUR PKGBUILD binary install path

### ISSUE THREAD

**Issue by shvedes** [gabrielzschmitz/Tomato.C#54]
Why are binaries installed in `/usr/local/bin` instead of `/usr/bin`? Typically this directory contains scripts and binaries placed by the system administrator, but not by the package manager.

I'm writing this here because the PKGBUILD states that you are the maintainer.

**Comment by gabrielzschmitz** [comment]
I've seen that suckless programs, normally are install that way. But no problem installing at /usr/bin too...

**Comment by shvedes** [comment]
Well, that's why i have to edit PKGBUILD and keep it on my disk ¯\_(ツ)_/¯

**Comment by gabrielzschmitz** [comment]
I actually cant make changes to the AUR package anymore for some months. I've lost my gpg keys...
But I really recommend you to git clone and maintain a copy of the code so you can edit and recompile the app. I'll recreate the AUR package as soon as I end the app rewrite, sorry
