### ISSUE TITLE
After closing Tomato with q, terminal starts spamming gibberish

### ISSUE THREAD

**Issue by writeblankspace** [gabrielzschmitz/Tomato.C#9]
![image](https://user-images.githubusercontent.com/75297066/212261838-5f6ae785-666f-4797-a200-b3d49a3296d3.png)

Not touching my keyboard nor does this happen in any other apps. Starting with a fresh terminal solves it, but after opening and closing Tomato it happens again. Not sure if it's Tomato's fault, but it only started after I installed Tomato.

**Comment by gabrielzschmitz** [comment]
This happen in which application? I need to reproduce the error

**Comment by gabrielzschmitz** [comment]
```c
        case ESC:
        case 'Q':
        case 'q':
            endwin();
+           /* Makes terminal stop reporting mouse movement events */
+           printf("\033[?1003l\n");
            exit(EXIT_SUCCESS);
            break;
```

Try to add that 2 lines in `input.c` and give a feedback
